/* tslint:disable */
/* eslint-disable */
/**
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Persisted storage backend for the sandbox
 */

export const SandboxStorageBackend = {
    COS: 'cos',
    LOCAL: 'local',
    UNKNOWN_DEFAULT_OPEN_API: '11184809',
} as const;

export type SandboxStorageBackend = typeof SandboxStorageBackend[keyof typeof SandboxStorageBackend];
