/*
 * Daytona
 * Daytona AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.daytona.api.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Persisted storage backend for the sandbox
 */
@JsonAdapter(SandboxStorageBackend.Adapter.class)
public enum SandboxStorageBackend {

  COS("cos"),

  LOCAL("local"),

  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  SandboxStorageBackend(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SandboxStorageBackend fromValue(String value) {
    for (SandboxStorageBackend b : SandboxStorageBackend.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<SandboxStorageBackend> {
    @Override
    public void write(final JsonWriter jsonWriter, final SandboxStorageBackend enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SandboxStorageBackend read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SandboxStorageBackend.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SandboxStorageBackend.fromValue(value);
  }
}
