/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type StorageWorkspacesAPI interface {

	/*
	GetWorkspaceMove Get workspace move status

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param sandboxId
	@param operationId
	@return StorageWorkspacesAPIGetWorkspaceMoveRequest
	*/
	GetWorkspaceMove(ctx context.Context, sandboxId string, operationId string) StorageWorkspacesAPIGetWorkspaceMoveRequest

	// GetWorkspaceMoveExecute executes the request
	//  @return WorkspaceOperationDto
	GetWorkspaceMoveExecute(r StorageWorkspacesAPIGetWorkspaceMoveRequest) (*WorkspaceOperationDto, *http.Response, error)

	/*
	RequestWorkspaceMove Request an idempotent workspace move

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param sandboxId
	@return StorageWorkspacesAPIRequestWorkspaceMoveRequest
	*/
	RequestWorkspaceMove(ctx context.Context, sandboxId string) StorageWorkspacesAPIRequestWorkspaceMoveRequest

	// RequestWorkspaceMoveExecute executes the request
	//  @return WorkspaceOperationDto
	RequestWorkspaceMoveExecute(r StorageWorkspacesAPIRequestWorkspaceMoveRequest) (*WorkspaceOperationDto, *http.Response, error)
}

// StorageWorkspacesAPIService StorageWorkspacesAPI service
type StorageWorkspacesAPIService service

type StorageWorkspacesAPIGetWorkspaceMoveRequest struct {
	ctx context.Context
	ApiService StorageWorkspacesAPI
	sandboxId string
	operationId string
	xDaytonaOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r StorageWorkspacesAPIGetWorkspaceMoveRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) StorageWorkspacesAPIGetWorkspaceMoveRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r StorageWorkspacesAPIGetWorkspaceMoveRequest) Execute() (*WorkspaceOperationDto, *http.Response, error) {
	return r.ApiService.GetWorkspaceMoveExecute(r)
}

/*
GetWorkspaceMove Get workspace move status

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param sandboxId
 @param operationId
 @return StorageWorkspacesAPIGetWorkspaceMoveRequest
*/
func (a *StorageWorkspacesAPIService) GetWorkspaceMove(ctx context.Context, sandboxId string, operationId string) StorageWorkspacesAPIGetWorkspaceMoveRequest {
	return StorageWorkspacesAPIGetWorkspaceMoveRequest{
		ApiService: a,
		ctx: ctx,
		sandboxId: sandboxId,
		operationId: operationId,
	}
}

// Execute executes the request
//  @return WorkspaceOperationDto
func (a *StorageWorkspacesAPIService) GetWorkspaceMoveExecute(r StorageWorkspacesAPIGetWorkspaceMoveRequest) (*WorkspaceOperationDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkspaceOperationDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageWorkspacesAPIService.GetWorkspaceMove")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/storage-workspaces/{sandboxId}/operations/{operationId}"
	localVarPath = strings.Replace(localVarPath, "{"+"sandboxId"+"}", url.PathEscape(parameterValueToString(r.sandboxId, "sandboxId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"operationId"+"}", url.PathEscape(parameterValueToString(r.operationId, "operationId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type StorageWorkspacesAPIRequestWorkspaceMoveRequest struct {
	ctx context.Context
	ApiService StorageWorkspacesAPI
	sandboxId string
	requestWorkspaceMoveDto *RequestWorkspaceMoveDto
	xDaytonaOrganizationID *string
}

func (r StorageWorkspacesAPIRequestWorkspaceMoveRequest) RequestWorkspaceMoveDto(requestWorkspaceMoveDto RequestWorkspaceMoveDto) StorageWorkspacesAPIRequestWorkspaceMoveRequest {
	r.requestWorkspaceMoveDto = &requestWorkspaceMoveDto
	return r
}

// Use with JWT to specify the organization ID
func (r StorageWorkspacesAPIRequestWorkspaceMoveRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) StorageWorkspacesAPIRequestWorkspaceMoveRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r StorageWorkspacesAPIRequestWorkspaceMoveRequest) Execute() (*WorkspaceOperationDto, *http.Response, error) {
	return r.ApiService.RequestWorkspaceMoveExecute(r)
}

/*
RequestWorkspaceMove Request an idempotent workspace move

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param sandboxId
 @return StorageWorkspacesAPIRequestWorkspaceMoveRequest
*/
func (a *StorageWorkspacesAPIService) RequestWorkspaceMove(ctx context.Context, sandboxId string) StorageWorkspacesAPIRequestWorkspaceMoveRequest {
	return StorageWorkspacesAPIRequestWorkspaceMoveRequest{
		ApiService: a,
		ctx: ctx,
		sandboxId: sandboxId,
	}
}

// Execute executes the request
//  @return WorkspaceOperationDto
func (a *StorageWorkspacesAPIService) RequestWorkspaceMoveExecute(r StorageWorkspacesAPIRequestWorkspaceMoveRequest) (*WorkspaceOperationDto, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *WorkspaceOperationDto
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageWorkspacesAPIService.RequestWorkspaceMove")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/storage-workspaces/{sandboxId}/move"
	localVarPath = strings.Replace(localVarPath, "{"+"sandboxId"+"}", url.PathEscape(parameterValueToString(r.sandboxId, "sandboxId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestWorkspaceMoveDto == nil {
		return localVarReturnValue, nil, reportError("requestWorkspaceMoveDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	// body params
	localVarPostBody = r.requestWorkspaceMoveDto
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
