/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type StorageNodesAPI interface {

	/*
	ActivateStorageNode Activate a storage node

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param runnerId Runner resource that owns the node
	@param nodeId Stable storage node identifier
	@return StorageNodesAPIActivateStorageNodeRequest
	*/
	ActivateStorageNode(ctx context.Context, runnerId string, nodeId string) StorageNodesAPIActivateStorageNodeRequest

	// ActivateStorageNodeExecute executes the request
	//  @return StorageNode
	ActivateStorageNodeExecute(r StorageNodesAPIActivateStorageNodeRequest) (*StorageNode, *http.Response, error)

	/*
	CordonStorageNode Cordon a storage node

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param runnerId Runner resource that owns the node
	@param nodeId Stable storage node identifier
	@return StorageNodesAPICordonStorageNodeRequest
	*/
	CordonStorageNode(ctx context.Context, runnerId string, nodeId string) StorageNodesAPICordonStorageNodeRequest

	// CordonStorageNodeExecute executes the request
	//  @return StorageNode
	CordonStorageNodeExecute(r StorageNodesAPICordonStorageNodeRequest) (*StorageNode, *http.Response, error)

	/*
	DrainStorageNode Start draining a storage node

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param runnerId Runner resource that owns the node
	@param nodeId Stable storage node identifier
	@return StorageNodesAPIDrainStorageNodeRequest
	*/
	DrainStorageNode(ctx context.Context, runnerId string, nodeId string) StorageNodesAPIDrainStorageNodeRequest

	// DrainStorageNodeExecute executes the request
	//  @return StorageNode
	DrainStorageNodeExecute(r StorageNodesAPIDrainStorageNodeRequest) (*StorageNode, *http.Response, error)

	/*
	GetStorageNodeStatus Get storage node status

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param runnerId Runner resource that owns the node
	@param nodeId Stable storage node identifier
	@return StorageNodesAPIGetStorageNodeStatusRequest
	*/
	GetStorageNodeStatus(ctx context.Context, runnerId string, nodeId string) StorageNodesAPIGetStorageNodeStatusRequest

	// GetStorageNodeStatusExecute executes the request
	//  @return StorageNode
	GetStorageNodeStatusExecute(r StorageNodesAPIGetStorageNodeStatusRequest) (*StorageNode, *http.Response, error)

	/*
	HeartbeatStorageNode Record storage capacity and heartbeat for the authenticated Runner

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param nodeId Stable storage node identifier
	@return StorageNodesAPIHeartbeatStorageNodeRequest
	*/
	HeartbeatStorageNode(ctx context.Context, nodeId string) StorageNodesAPIHeartbeatStorageNodeRequest

	// HeartbeatStorageNodeExecute executes the request
	//  @return StorageNode
	HeartbeatStorageNodeExecute(r StorageNodesAPIHeartbeatStorageNodeRequest) (*StorageNode, *http.Response, error)

	/*
	RegisterStorageNode Register the authenticated Runner storage node

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return StorageNodesAPIRegisterStorageNodeRequest
	*/
	RegisterStorageNode(ctx context.Context) StorageNodesAPIRegisterStorageNodeRequest

	// RegisterStorageNodeExecute executes the request
	//  @return StorageNode
	RegisterStorageNodeExecute(r StorageNodesAPIRegisterStorageNodeRequest) (*StorageNode, *http.Response, error)

	/*
	RemoveStorageNode Tombstone a drained storage node

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param runnerId Runner resource that owns the node
	@param nodeId Stable storage node identifier
	@return StorageNodesAPIRemoveStorageNodeRequest
	*/
	RemoveStorageNode(ctx context.Context, runnerId string, nodeId string) StorageNodesAPIRemoveStorageNodeRequest

	// RemoveStorageNodeExecute executes the request
	//  @return StorageNode
	RemoveStorageNodeExecute(r StorageNodesAPIRemoveStorageNodeRequest) (*StorageNode, *http.Response, error)
}

// StorageNodesAPIService StorageNodesAPI service
type StorageNodesAPIService service

type StorageNodesAPIActivateStorageNodeRequest struct {
	ctx context.Context
	ApiService StorageNodesAPI
	runnerId string
	nodeId string
	xDaytonaOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r StorageNodesAPIActivateStorageNodeRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) StorageNodesAPIActivateStorageNodeRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r StorageNodesAPIActivateStorageNodeRequest) Execute() (*StorageNode, *http.Response, error) {
	return r.ApiService.ActivateStorageNodeExecute(r)
}

/*
ActivateStorageNode Activate a storage node

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param runnerId Runner resource that owns the node
 @param nodeId Stable storage node identifier
 @return StorageNodesAPIActivateStorageNodeRequest
*/
func (a *StorageNodesAPIService) ActivateStorageNode(ctx context.Context, runnerId string, nodeId string) StorageNodesAPIActivateStorageNodeRequest {
	return StorageNodesAPIActivateStorageNodeRequest{
		ApiService: a,
		ctx: ctx,
		runnerId: runnerId,
		nodeId: nodeId,
	}
}

// Execute executes the request
//  @return StorageNode
func (a *StorageNodesAPIService) ActivateStorageNodeExecute(r StorageNodesAPIActivateStorageNodeRequest) (*StorageNode, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *StorageNode
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageNodesAPIService.ActivateStorageNode")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners/{runnerId}/storage-nodes/{nodeId}/activate"
	localVarPath = strings.Replace(localVarPath, "{"+"runnerId"+"}", url.PathEscape(parameterValueToString(r.runnerId, "runnerId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"nodeId"+"}", url.PathEscape(parameterValueToString(r.nodeId, "nodeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type StorageNodesAPICordonStorageNodeRequest struct {
	ctx context.Context
	ApiService StorageNodesAPI
	runnerId string
	nodeId string
	xDaytonaOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r StorageNodesAPICordonStorageNodeRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) StorageNodesAPICordonStorageNodeRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r StorageNodesAPICordonStorageNodeRequest) Execute() (*StorageNode, *http.Response, error) {
	return r.ApiService.CordonStorageNodeExecute(r)
}

/*
CordonStorageNode Cordon a storage node

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param runnerId Runner resource that owns the node
 @param nodeId Stable storage node identifier
 @return StorageNodesAPICordonStorageNodeRequest
*/
func (a *StorageNodesAPIService) CordonStorageNode(ctx context.Context, runnerId string, nodeId string) StorageNodesAPICordonStorageNodeRequest {
	return StorageNodesAPICordonStorageNodeRequest{
		ApiService: a,
		ctx: ctx,
		runnerId: runnerId,
		nodeId: nodeId,
	}
}

// Execute executes the request
//  @return StorageNode
func (a *StorageNodesAPIService) CordonStorageNodeExecute(r StorageNodesAPICordonStorageNodeRequest) (*StorageNode, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *StorageNode
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageNodesAPIService.CordonStorageNode")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners/{runnerId}/storage-nodes/{nodeId}/cordon"
	localVarPath = strings.Replace(localVarPath, "{"+"runnerId"+"}", url.PathEscape(parameterValueToString(r.runnerId, "runnerId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"nodeId"+"}", url.PathEscape(parameterValueToString(r.nodeId, "nodeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type StorageNodesAPIDrainStorageNodeRequest struct {
	ctx context.Context
	ApiService StorageNodesAPI
	runnerId string
	nodeId string
	xDaytonaOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r StorageNodesAPIDrainStorageNodeRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) StorageNodesAPIDrainStorageNodeRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r StorageNodesAPIDrainStorageNodeRequest) Execute() (*StorageNode, *http.Response, error) {
	return r.ApiService.DrainStorageNodeExecute(r)
}

/*
DrainStorageNode Start draining a storage node

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param runnerId Runner resource that owns the node
 @param nodeId Stable storage node identifier
 @return StorageNodesAPIDrainStorageNodeRequest
*/
func (a *StorageNodesAPIService) DrainStorageNode(ctx context.Context, runnerId string, nodeId string) StorageNodesAPIDrainStorageNodeRequest {
	return StorageNodesAPIDrainStorageNodeRequest{
		ApiService: a,
		ctx: ctx,
		runnerId: runnerId,
		nodeId: nodeId,
	}
}

// Execute executes the request
//  @return StorageNode
func (a *StorageNodesAPIService) DrainStorageNodeExecute(r StorageNodesAPIDrainStorageNodeRequest) (*StorageNode, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *StorageNode
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageNodesAPIService.DrainStorageNode")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners/{runnerId}/storage-nodes/{nodeId}/drain"
	localVarPath = strings.Replace(localVarPath, "{"+"runnerId"+"}", url.PathEscape(parameterValueToString(r.runnerId, "runnerId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"nodeId"+"}", url.PathEscape(parameterValueToString(r.nodeId, "nodeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type StorageNodesAPIGetStorageNodeStatusRequest struct {
	ctx context.Context
	ApiService StorageNodesAPI
	runnerId string
	nodeId string
	xDaytonaOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r StorageNodesAPIGetStorageNodeStatusRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) StorageNodesAPIGetStorageNodeStatusRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r StorageNodesAPIGetStorageNodeStatusRequest) Execute() (*StorageNode, *http.Response, error) {
	return r.ApiService.GetStorageNodeStatusExecute(r)
}

/*
GetStorageNodeStatus Get storage node status

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param runnerId Runner resource that owns the node
 @param nodeId Stable storage node identifier
 @return StorageNodesAPIGetStorageNodeStatusRequest
*/
func (a *StorageNodesAPIService) GetStorageNodeStatus(ctx context.Context, runnerId string, nodeId string) StorageNodesAPIGetStorageNodeStatusRequest {
	return StorageNodesAPIGetStorageNodeStatusRequest{
		ApiService: a,
		ctx: ctx,
		runnerId: runnerId,
		nodeId: nodeId,
	}
}

// Execute executes the request
//  @return StorageNode
func (a *StorageNodesAPIService) GetStorageNodeStatusExecute(r StorageNodesAPIGetStorageNodeStatusRequest) (*StorageNode, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *StorageNode
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageNodesAPIService.GetStorageNodeStatus")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners/{runnerId}/storage-nodes/{nodeId}"
	localVarPath = strings.Replace(localVarPath, "{"+"runnerId"+"}", url.PathEscape(parameterValueToString(r.runnerId, "runnerId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"nodeId"+"}", url.PathEscape(parameterValueToString(r.nodeId, "nodeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type StorageNodesAPIHeartbeatStorageNodeRequest struct {
	ctx context.Context
	ApiService StorageNodesAPI
	nodeId string
	heartbeatStorageNode *HeartbeatStorageNode
}

func (r StorageNodesAPIHeartbeatStorageNodeRequest) HeartbeatStorageNode(heartbeatStorageNode HeartbeatStorageNode) StorageNodesAPIHeartbeatStorageNodeRequest {
	r.heartbeatStorageNode = &heartbeatStorageNode
	return r
}

func (r StorageNodesAPIHeartbeatStorageNodeRequest) Execute() (*StorageNode, *http.Response, error) {
	return r.ApiService.HeartbeatStorageNodeExecute(r)
}

/*
HeartbeatStorageNode Record storage capacity and heartbeat for the authenticated Runner

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param nodeId Stable storage node identifier
 @return StorageNodesAPIHeartbeatStorageNodeRequest
*/
func (a *StorageNodesAPIService) HeartbeatStorageNode(ctx context.Context, nodeId string) StorageNodesAPIHeartbeatStorageNodeRequest {
	return StorageNodesAPIHeartbeatStorageNodeRequest{
		ApiService: a,
		ctx: ctx,
		nodeId: nodeId,
	}
}

// Execute executes the request
//  @return StorageNode
func (a *StorageNodesAPIService) HeartbeatStorageNodeExecute(r StorageNodesAPIHeartbeatStorageNodeRequest) (*StorageNode, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *StorageNode
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageNodesAPIService.HeartbeatStorageNode")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/storage-nodes/{nodeId}/heartbeat"
	localVarPath = strings.Replace(localVarPath, "{"+"nodeId"+"}", url.PathEscape(parameterValueToString(r.nodeId, "nodeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.heartbeatStorageNode == nil {
		return localVarReturnValue, nil, reportError("heartbeatStorageNode is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.heartbeatStorageNode
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type StorageNodesAPIRegisterStorageNodeRequest struct {
	ctx context.Context
	ApiService StorageNodesAPI
	registerStorageNode *RegisterStorageNode
}

func (r StorageNodesAPIRegisterStorageNodeRequest) RegisterStorageNode(registerStorageNode RegisterStorageNode) StorageNodesAPIRegisterStorageNodeRequest {
	r.registerStorageNode = &registerStorageNode
	return r
}

func (r StorageNodesAPIRegisterStorageNodeRequest) Execute() (*StorageNode, *http.Response, error) {
	return r.ApiService.RegisterStorageNodeExecute(r)
}

/*
RegisterStorageNode Register the authenticated Runner storage node

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return StorageNodesAPIRegisterStorageNodeRequest
*/
func (a *StorageNodesAPIService) RegisterStorageNode(ctx context.Context) StorageNodesAPIRegisterStorageNodeRequest {
	return StorageNodesAPIRegisterStorageNodeRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return StorageNode
func (a *StorageNodesAPIService) RegisterStorageNodeExecute(r StorageNodesAPIRegisterStorageNodeRequest) (*StorageNode, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *StorageNode
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageNodesAPIService.RegisterStorageNode")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/storage-nodes/register"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.registerStorageNode == nil {
		return localVarReturnValue, nil, reportError("registerStorageNode is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.registerStorageNode
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type StorageNodesAPIRemoveStorageNodeRequest struct {
	ctx context.Context
	ApiService StorageNodesAPI
	runnerId string
	nodeId string
	xDaytonaOrganizationID *string
}

// Use with JWT to specify the organization ID
func (r StorageNodesAPIRemoveStorageNodeRequest) XDaytonaOrganizationID(xDaytonaOrganizationID string) StorageNodesAPIRemoveStorageNodeRequest {
	r.xDaytonaOrganizationID = &xDaytonaOrganizationID
	return r
}

func (r StorageNodesAPIRemoveStorageNodeRequest) Execute() (*StorageNode, *http.Response, error) {
	return r.ApiService.RemoveStorageNodeExecute(r)
}

/*
RemoveStorageNode Tombstone a drained storage node

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param runnerId Runner resource that owns the node
 @param nodeId Stable storage node identifier
 @return StorageNodesAPIRemoveStorageNodeRequest
*/
func (a *StorageNodesAPIService) RemoveStorageNode(ctx context.Context, runnerId string, nodeId string) StorageNodesAPIRemoveStorageNodeRequest {
	return StorageNodesAPIRemoveStorageNodeRequest{
		ApiService: a,
		ctx: ctx,
		runnerId: runnerId,
		nodeId: nodeId,
	}
}

// Execute executes the request
//  @return StorageNode
func (a *StorageNodesAPIService) RemoveStorageNodeExecute(r StorageNodesAPIRemoveStorageNodeRequest) (*StorageNode, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *StorageNode
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StorageNodesAPIService.RemoveStorageNode")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners/{runnerId}/storage-nodes/{nodeId}/remove"
	localVarPath = strings.Replace(localVarPath, "{"+"runnerId"+"}", url.PathEscape(parameterValueToString(r.runnerId, "runnerId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"nodeId"+"}", url.PathEscape(parameterValueToString(r.nodeId, "nodeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xDaytonaOrganizationID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "X-Daytona-Organization-ID", r.xDaytonaOrganizationID, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
