/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the RegisterStorageNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterStorageNode{}

// RegisterStorageNode struct for RegisterStorageNode
type RegisterStorageNode struct {
	// Stable storage node identifier
	NodeId string `json:"nodeId"`
	// Total bytes available to the node
	CapacityBytes float32 `json:"capacityBytes"`
	// Total inodes available to the node
	CapacityInodes float32 `json:"capacityInodes"`
	// Non-sensitive scheduling labels
	Labels map[string]interface{} `json:"labels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RegisterStorageNode RegisterStorageNode

// NewRegisterStorageNode instantiates a new RegisterStorageNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterStorageNode(nodeId string, capacityBytes float32, capacityInodes float32) *RegisterStorageNode {
	this := RegisterStorageNode{}
	this.NodeId = nodeId
	this.CapacityBytes = capacityBytes
	this.CapacityInodes = capacityInodes
	return &this
}

// NewRegisterStorageNodeWithDefaults instantiates a new RegisterStorageNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterStorageNodeWithDefaults() *RegisterStorageNode {
	this := RegisterStorageNode{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *RegisterStorageNode) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *RegisterStorageNode) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *RegisterStorageNode) SetNodeId(v string) {
	o.NodeId = v
}

// GetCapacityBytes returns the CapacityBytes field value
func (o *RegisterStorageNode) GetCapacityBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CapacityBytes
}

// GetCapacityBytesOk returns a tuple with the CapacityBytes field value
// and a boolean to check if the value has been set.
func (o *RegisterStorageNode) GetCapacityBytesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapacityBytes, true
}

// SetCapacityBytes sets field value
func (o *RegisterStorageNode) SetCapacityBytes(v float32) {
	o.CapacityBytes = v
}

// GetCapacityInodes returns the CapacityInodes field value
func (o *RegisterStorageNode) GetCapacityInodes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CapacityInodes
}

// GetCapacityInodesOk returns a tuple with the CapacityInodes field value
// and a boolean to check if the value has been set.
func (o *RegisterStorageNode) GetCapacityInodesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapacityInodes, true
}

// SetCapacityInodes sets field value
func (o *RegisterStorageNode) SetCapacityInodes(v float32) {
	o.CapacityInodes = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *RegisterStorageNode) GetLabels() map[string]interface{} {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]interface{}
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterStorageNode) GetLabelsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]interface{}{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *RegisterStorageNode) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]interface{} and assigns it to the Labels field.
func (o *RegisterStorageNode) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

func (o RegisterStorageNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterStorageNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodeId"] = o.NodeId
	toSerialize["capacityBytes"] = o.CapacityBytes
	toSerialize["capacityInodes"] = o.CapacityInodes
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegisterStorageNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nodeId",
		"capacityBytes",
		"capacityInodes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterStorageNode := _RegisterStorageNode{}

	err = json.Unmarshal(data, &varRegisterStorageNode)

	if err != nil {
		return err
	}

	*o = RegisterStorageNode(varRegisterStorageNode)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nodeId")
		delete(additionalProperties, "capacityBytes")
		delete(additionalProperties, "capacityInodes")
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegisterStorageNode struct {
	value *RegisterStorageNode
	isSet bool
}

func (v NullableRegisterStorageNode) Get() *RegisterStorageNode {
	return v.value
}

func (v *NullableRegisterStorageNode) Set(val *RegisterStorageNode) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterStorageNode) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterStorageNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterStorageNode(val *RegisterStorageNode) *NullableRegisterStorageNode {
	return &NullableRegisterStorageNode{value: val, isSet: true}
}

func (v NullableRegisterStorageNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterStorageNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
