/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the WorkspaceOperationDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceOperationDto{}

// WorkspaceOperationDto struct for WorkspaceOperationDto
type WorkspaceOperationDto struct {
	Id string `json:"id"`
	Phase string `json:"phase"`
	PlacementId string `json:"placementId"`
	SandboxId string `json:"sandboxId"`
	SourceNodeId string `json:"sourceNodeId"`
	TargetNodeId string `json:"targetNodeId"`
	ErrorCode NullableString `json:"errorCode"`
	SourceRetained bool `json:"sourceRetained"`
	AdditionalProperties map[string]interface{}
}

type _WorkspaceOperationDto WorkspaceOperationDto

// NewWorkspaceOperationDto instantiates a new WorkspaceOperationDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceOperationDto(id string, phase string, placementId string, sandboxId string, sourceNodeId string, targetNodeId string, errorCode NullableString, sourceRetained bool) *WorkspaceOperationDto {
	this := WorkspaceOperationDto{}
	this.Id = id
	this.Phase = phase
	this.PlacementId = placementId
	this.SandboxId = sandboxId
	this.SourceNodeId = sourceNodeId
	this.TargetNodeId = targetNodeId
	this.ErrorCode = errorCode
	this.SourceRetained = sourceRetained
	return &this
}

// NewWorkspaceOperationDtoWithDefaults instantiates a new WorkspaceOperationDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceOperationDtoWithDefaults() *WorkspaceOperationDto {
	this := WorkspaceOperationDto{}
	return &this
}

// GetId returns the Id field value
func (o *WorkspaceOperationDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkspaceOperationDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkspaceOperationDto) SetId(v string) {
	o.Id = v
}

// GetPhase returns the Phase field value
func (o *WorkspaceOperationDto) GetPhase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value
// and a boolean to check if the value has been set.
func (o *WorkspaceOperationDto) GetPhaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase, true
}

// SetPhase sets field value
func (o *WorkspaceOperationDto) SetPhase(v string) {
	o.Phase = v
}

// GetPlacementId returns the PlacementId field value
func (o *WorkspaceOperationDto) GetPlacementId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlacementId
}

// GetPlacementIdOk returns a tuple with the PlacementId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceOperationDto) GetPlacementIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlacementId, true
}

// SetPlacementId sets field value
func (o *WorkspaceOperationDto) SetPlacementId(v string) {
	o.PlacementId = v
}

// GetSandboxId returns the SandboxId field value
func (o *WorkspaceOperationDto) GetSandboxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SandboxId
}

// GetSandboxIdOk returns a tuple with the SandboxId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceOperationDto) GetSandboxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SandboxId, true
}

// SetSandboxId sets field value
func (o *WorkspaceOperationDto) SetSandboxId(v string) {
	o.SandboxId = v
}

// GetSourceNodeId returns the SourceNodeId field value
func (o *WorkspaceOperationDto) GetSourceNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceNodeId
}

// GetSourceNodeIdOk returns a tuple with the SourceNodeId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceOperationDto) GetSourceNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceNodeId, true
}

// SetSourceNodeId sets field value
func (o *WorkspaceOperationDto) SetSourceNodeId(v string) {
	o.SourceNodeId = v
}

// GetTargetNodeId returns the TargetNodeId field value
func (o *WorkspaceOperationDto) GetTargetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetNodeId
}

// GetTargetNodeIdOk returns a tuple with the TargetNodeId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceOperationDto) GetTargetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetNodeId, true
}

// SetTargetNodeId sets field value
func (o *WorkspaceOperationDto) SetTargetNodeId(v string) {
	o.TargetNodeId = v
}

// GetErrorCode returns the ErrorCode field value
// If the value is explicit nil, the zero value for string will be returned
func (o *WorkspaceOperationDto) GetErrorCode() string {
	if o == nil || o.ErrorCode.Get() == nil {
		var ret string
		return ret
	}

	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkspaceOperationDto) GetErrorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// SetErrorCode sets field value
func (o *WorkspaceOperationDto) SetErrorCode(v string) {
	o.ErrorCode.Set(&v)
}

// GetSourceRetained returns the SourceRetained field value
func (o *WorkspaceOperationDto) GetSourceRetained() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SourceRetained
}

// GetSourceRetainedOk returns a tuple with the SourceRetained field value
// and a boolean to check if the value has been set.
func (o *WorkspaceOperationDto) GetSourceRetainedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRetained, true
}

// SetSourceRetained sets field value
func (o *WorkspaceOperationDto) SetSourceRetained(v bool) {
	o.SourceRetained = v
}

func (o WorkspaceOperationDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceOperationDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["phase"] = o.Phase
	toSerialize["placementId"] = o.PlacementId
	toSerialize["sandboxId"] = o.SandboxId
	toSerialize["sourceNodeId"] = o.SourceNodeId
	toSerialize["targetNodeId"] = o.TargetNodeId
	toSerialize["errorCode"] = o.ErrorCode.Get()
	toSerialize["sourceRetained"] = o.SourceRetained

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkspaceOperationDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"phase",
		"placementId",
		"sandboxId",
		"sourceNodeId",
		"targetNodeId",
		"errorCode",
		"sourceRetained",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspaceOperationDto := _WorkspaceOperationDto{}

	err = json.Unmarshal(data, &varWorkspaceOperationDto)

	if err != nil {
		return err
	}

	*o = WorkspaceOperationDto(varWorkspaceOperationDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "phase")
		delete(additionalProperties, "placementId")
		delete(additionalProperties, "sandboxId")
		delete(additionalProperties, "sourceNodeId")
		delete(additionalProperties, "targetNodeId")
		delete(additionalProperties, "errorCode")
		delete(additionalProperties, "sourceRetained")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkspaceOperationDto struct {
	value *WorkspaceOperationDto
	isSet bool
}

func (v NullableWorkspaceOperationDto) Get() *WorkspaceOperationDto {
	return v.value
}

func (v *NullableWorkspaceOperationDto) Set(val *WorkspaceOperationDto) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceOperationDto) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceOperationDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceOperationDto(val *WorkspaceOperationDto) *NullableWorkspaceOperationDto {
	return &NullableWorkspaceOperationDto{value: val, isSet: true}
}

func (v NullableWorkspaceOperationDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceOperationDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
