/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the StorageNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageNode{}

// StorageNode struct for StorageNode
type StorageNode struct {
	NodeId string `json:"nodeId"`
	RunnerId string `json:"runnerId"`
	State string `json:"state"`
	// Bigint values are returned as decimal strings
	CapacityBytes string `json:"capacityBytes"`
	// Bigint values are returned as decimal strings
	UsedBytes string `json:"usedBytes"`
	// Bigint values are returned as decimal strings
	CapacityInodes string `json:"capacityInodes"`
	// Bigint values are returned as decimal strings
	UsedInodes string `json:"usedInodes"`
	Labels map[string]interface{} `json:"labels"`
	HeartbeatAt NullableTime `json:"heartbeatAt,omitempty"`
	RemovedAt NullableTime `json:"removedAt,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _StorageNode StorageNode

// NewStorageNode instantiates a new StorageNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageNode(nodeId string, runnerId string, state string, capacityBytes string, usedBytes string, capacityInodes string, usedInodes string, labels map[string]interface{}, createdAt time.Time, updatedAt time.Time) *StorageNode {
	this := StorageNode{}
	this.NodeId = nodeId
	this.RunnerId = runnerId
	this.State = state
	this.CapacityBytes = capacityBytes
	this.UsedBytes = usedBytes
	this.CapacityInodes = capacityInodes
	this.UsedInodes = usedInodes
	this.Labels = labels
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewStorageNodeWithDefaults instantiates a new StorageNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageNodeWithDefaults() *StorageNode {
	this := StorageNode{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *StorageNode) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *StorageNode) SetNodeId(v string) {
	o.NodeId = v
}

// GetRunnerId returns the RunnerId field value
func (o *StorageNode) GetRunnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunnerId
}

// GetRunnerIdOk returns a tuple with the RunnerId field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetRunnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunnerId, true
}

// SetRunnerId sets field value
func (o *StorageNode) SetRunnerId(v string) {
	o.RunnerId = v
}

// GetState returns the State field value
func (o *StorageNode) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *StorageNode) SetState(v string) {
	o.State = v
}

// GetCapacityBytes returns the CapacityBytes field value
func (o *StorageNode) GetCapacityBytes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CapacityBytes
}

// GetCapacityBytesOk returns a tuple with the CapacityBytes field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetCapacityBytesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapacityBytes, true
}

// SetCapacityBytes sets field value
func (o *StorageNode) SetCapacityBytes(v string) {
	o.CapacityBytes = v
}

// GetUsedBytes returns the UsedBytes field value
func (o *StorageNode) GetUsedBytes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UsedBytes
}

// GetUsedBytesOk returns a tuple with the UsedBytes field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetUsedBytesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedBytes, true
}

// SetUsedBytes sets field value
func (o *StorageNode) SetUsedBytes(v string) {
	o.UsedBytes = v
}

// GetCapacityInodes returns the CapacityInodes field value
func (o *StorageNode) GetCapacityInodes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CapacityInodes
}

// GetCapacityInodesOk returns a tuple with the CapacityInodes field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetCapacityInodesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapacityInodes, true
}

// SetCapacityInodes sets field value
func (o *StorageNode) SetCapacityInodes(v string) {
	o.CapacityInodes = v
}

// GetUsedInodes returns the UsedInodes field value
func (o *StorageNode) GetUsedInodes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UsedInodes
}

// GetUsedInodesOk returns a tuple with the UsedInodes field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetUsedInodesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedInodes, true
}

// SetUsedInodes sets field value
func (o *StorageNode) SetUsedInodes(v string) {
	o.UsedInodes = v
}

// GetLabels returns the Labels field value
func (o *StorageNode) GetLabels() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetLabelsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *StorageNode) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

// GetHeartbeatAt returns the HeartbeatAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StorageNode) GetHeartbeatAt() time.Time {
	if o == nil || IsNil(o.HeartbeatAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.HeartbeatAt.Get()
}

// GetHeartbeatAtOk returns a tuple with the HeartbeatAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StorageNode) GetHeartbeatAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.HeartbeatAt.Get(), o.HeartbeatAt.IsSet()
}

// HasHeartbeatAt returns a boolean if a field has been set.
func (o *StorageNode) HasHeartbeatAt() bool {
	if o != nil && o.HeartbeatAt.IsSet() {
		return true
	}

	return false
}

// SetHeartbeatAt gets a reference to the given NullableTime and assigns it to the HeartbeatAt field.
func (o *StorageNode) SetHeartbeatAt(v time.Time) {
	o.HeartbeatAt.Set(&v)
}
// SetHeartbeatAtNil sets the value for HeartbeatAt to be an explicit nil
func (o *StorageNode) SetHeartbeatAtNil() {
	o.HeartbeatAt.Set(nil)
}

// UnsetHeartbeatAt ensures that no value is present for HeartbeatAt, not even an explicit nil
func (o *StorageNode) UnsetHeartbeatAt() {
	o.HeartbeatAt.Unset()
}

// GetRemovedAt returns the RemovedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StorageNode) GetRemovedAt() time.Time {
	if o == nil || IsNil(o.RemovedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RemovedAt.Get()
}

// GetRemovedAtOk returns a tuple with the RemovedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StorageNode) GetRemovedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemovedAt.Get(), o.RemovedAt.IsSet()
}

// HasRemovedAt returns a boolean if a field has been set.
func (o *StorageNode) HasRemovedAt() bool {
	if o != nil && o.RemovedAt.IsSet() {
		return true
	}

	return false
}

// SetRemovedAt gets a reference to the given NullableTime and assigns it to the RemovedAt field.
func (o *StorageNode) SetRemovedAt(v time.Time) {
	o.RemovedAt.Set(&v)
}
// SetRemovedAtNil sets the value for RemovedAt to be an explicit nil
func (o *StorageNode) SetRemovedAtNil() {
	o.RemovedAt.Set(nil)
}

// UnsetRemovedAt ensures that no value is present for RemovedAt, not even an explicit nil
func (o *StorageNode) UnsetRemovedAt() {
	o.RemovedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *StorageNode) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *StorageNode) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *StorageNode) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *StorageNode) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *StorageNode) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o StorageNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodeId"] = o.NodeId
	toSerialize["runnerId"] = o.RunnerId
	toSerialize["state"] = o.State
	toSerialize["capacityBytes"] = o.CapacityBytes
	toSerialize["usedBytes"] = o.UsedBytes
	toSerialize["capacityInodes"] = o.CapacityInodes
	toSerialize["usedInodes"] = o.UsedInodes
	toSerialize["labels"] = o.Labels
	if o.HeartbeatAt.IsSet() {
		toSerialize["heartbeatAt"] = o.HeartbeatAt.Get()
	}
	if o.RemovedAt.IsSet() {
		toSerialize["removedAt"] = o.RemovedAt.Get()
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StorageNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nodeId",
		"runnerId",
		"state",
		"capacityBytes",
		"usedBytes",
		"capacityInodes",
		"usedInodes",
		"labels",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageNode := _StorageNode{}

	err = json.Unmarshal(data, &varStorageNode)

	if err != nil {
		return err
	}

	*o = StorageNode(varStorageNode)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "nodeId")
		delete(additionalProperties, "runnerId")
		delete(additionalProperties, "state")
		delete(additionalProperties, "capacityBytes")
		delete(additionalProperties, "usedBytes")
		delete(additionalProperties, "capacityInodes")
		delete(additionalProperties, "usedInodes")
		delete(additionalProperties, "labels")
		delete(additionalProperties, "heartbeatAt")
		delete(additionalProperties, "removedAt")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStorageNode struct {
	value *StorageNode
	isSet bool
}

func (v NullableStorageNode) Get() *StorageNode {
	return v.value
}

func (v *NullableStorageNode) Set(val *StorageNode) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageNode) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageNode(val *StorageNode) *NullableStorageNode {
	return &NullableStorageNode{value: val, isSet: true}
}

func (v NullableStorageNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
