/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// SandboxStorageBackend Persisted storage backend for the sandbox
type SandboxStorageBackend string

// List of SandboxStorageBackend
const (
	SANDBOXSTORAGEBACKEND_COS                      SandboxStorageBackend = "cos"
	SANDBOXSTORAGEBACKEND_LOCAL                    SandboxStorageBackend = "local"
	SANDBOXSTORAGEBACKEND_UNKNOWN_DEFAULT_OPEN_API SandboxStorageBackend = "11184809"
)

// All allowed values of SandboxStorageBackend enum
var AllowedSandboxStorageBackendEnumValues = []SandboxStorageBackend{
	"cos",
	"local",
	"11184809",
}

func (v *SandboxStorageBackend) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SandboxStorageBackend(value)
	for _, existing := range AllowedSandboxStorageBackendEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	*v = SANDBOXSTORAGEBACKEND_UNKNOWN_DEFAULT_OPEN_API
	return nil
}

// NewSandboxStorageBackendFromValue returns a pointer to a valid SandboxStorageBackend
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSandboxStorageBackendFromValue(v string) (*SandboxStorageBackend, error) {
	ev := SandboxStorageBackend(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		enumValue := SANDBOXSTORAGEBACKEND_UNKNOWN_DEFAULT_OPEN_API
		return &enumValue, nil
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SandboxStorageBackend) IsValid() bool {
	for _, existing := range AllowedSandboxStorageBackendEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SandboxStorageBackend value
func (v SandboxStorageBackend) Ptr() *SandboxStorageBackend {
	return &v
}

type NullableSandboxStorageBackend struct {
	value *SandboxStorageBackend
	isSet bool
}

func (v NullableSandboxStorageBackend) Get() *SandboxStorageBackend {
	return v.value
}

func (v *NullableSandboxStorageBackend) Set(val *SandboxStorageBackend) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxStorageBackend) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxStorageBackend) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxStorageBackend(val *SandboxStorageBackend) *NullableSandboxStorageBackend {
	return &NullableSandboxStorageBackend{value: val, isSet: true}
}

func (v NullableSandboxStorageBackend) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxStorageBackend) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
