/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the RequestWorkspaceMoveDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestWorkspaceMoveDto{}

// RequestWorkspaceMoveDto struct for RequestWorkspaceMoveDto
type RequestWorkspaceMoveDto struct {
	OperationId string `json:"operationId"`
	PlacementId string `json:"placementId"`
	VolumeId string `json:"volumeId"`
	SourceNodeId string `json:"sourceNodeId"`
	TargetNodeId string `json:"targetNodeId"`
	ExpectedFenceEpoch string `json:"expectedFenceEpoch"`
	// Client retry key; it never authorizes a second move.
	IdempotencyKey string `json:"idempotencyKey"`
	AdditionalProperties map[string]interface{}
}

type _RequestWorkspaceMoveDto RequestWorkspaceMoveDto

// NewRequestWorkspaceMoveDto instantiates a new RequestWorkspaceMoveDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestWorkspaceMoveDto(operationId string, placementId string, volumeId string, sourceNodeId string, targetNodeId string, expectedFenceEpoch string, idempotencyKey string) *RequestWorkspaceMoveDto {
	this := RequestWorkspaceMoveDto{}
	this.OperationId = operationId
	this.PlacementId = placementId
	this.VolumeId = volumeId
	this.SourceNodeId = sourceNodeId
	this.TargetNodeId = targetNodeId
	this.ExpectedFenceEpoch = expectedFenceEpoch
	this.IdempotencyKey = idempotencyKey
	return &this
}

// NewRequestWorkspaceMoveDtoWithDefaults instantiates a new RequestWorkspaceMoveDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestWorkspaceMoveDtoWithDefaults() *RequestWorkspaceMoveDto {
	this := RequestWorkspaceMoveDto{}
	return &this
}

// GetOperationId returns the OperationId field value
func (o *RequestWorkspaceMoveDto) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *RequestWorkspaceMoveDto) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *RequestWorkspaceMoveDto) SetOperationId(v string) {
	o.OperationId = v
}

// GetPlacementId returns the PlacementId field value
func (o *RequestWorkspaceMoveDto) GetPlacementId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlacementId
}

// GetPlacementIdOk returns a tuple with the PlacementId field value
// and a boolean to check if the value has been set.
func (o *RequestWorkspaceMoveDto) GetPlacementIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlacementId, true
}

// SetPlacementId sets field value
func (o *RequestWorkspaceMoveDto) SetPlacementId(v string) {
	o.PlacementId = v
}

// GetVolumeId returns the VolumeId field value
func (o *RequestWorkspaceMoveDto) GetVolumeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VolumeId
}

// GetVolumeIdOk returns a tuple with the VolumeId field value
// and a boolean to check if the value has been set.
func (o *RequestWorkspaceMoveDto) GetVolumeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VolumeId, true
}

// SetVolumeId sets field value
func (o *RequestWorkspaceMoveDto) SetVolumeId(v string) {
	o.VolumeId = v
}

// GetSourceNodeId returns the SourceNodeId field value
func (o *RequestWorkspaceMoveDto) GetSourceNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceNodeId
}

// GetSourceNodeIdOk returns a tuple with the SourceNodeId field value
// and a boolean to check if the value has been set.
func (o *RequestWorkspaceMoveDto) GetSourceNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceNodeId, true
}

// SetSourceNodeId sets field value
func (o *RequestWorkspaceMoveDto) SetSourceNodeId(v string) {
	o.SourceNodeId = v
}

// GetTargetNodeId returns the TargetNodeId field value
func (o *RequestWorkspaceMoveDto) GetTargetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetNodeId
}

// GetTargetNodeIdOk returns a tuple with the TargetNodeId field value
// and a boolean to check if the value has been set.
func (o *RequestWorkspaceMoveDto) GetTargetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetNodeId, true
}

// SetTargetNodeId sets field value
func (o *RequestWorkspaceMoveDto) SetTargetNodeId(v string) {
	o.TargetNodeId = v
}

// GetExpectedFenceEpoch returns the ExpectedFenceEpoch field value
func (o *RequestWorkspaceMoveDto) GetExpectedFenceEpoch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedFenceEpoch
}

// GetExpectedFenceEpochOk returns a tuple with the ExpectedFenceEpoch field value
// and a boolean to check if the value has been set.
func (o *RequestWorkspaceMoveDto) GetExpectedFenceEpochOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedFenceEpoch, true
}

// SetExpectedFenceEpoch sets field value
func (o *RequestWorkspaceMoveDto) SetExpectedFenceEpoch(v string) {
	o.ExpectedFenceEpoch = v
}

// GetIdempotencyKey returns the IdempotencyKey field value
func (o *RequestWorkspaceMoveDto) GetIdempotencyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value
// and a boolean to check if the value has been set.
func (o *RequestWorkspaceMoveDto) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdempotencyKey, true
}

// SetIdempotencyKey sets field value
func (o *RequestWorkspaceMoveDto) SetIdempotencyKey(v string) {
	o.IdempotencyKey = v
}

func (o RequestWorkspaceMoveDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestWorkspaceMoveDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["operationId"] = o.OperationId
	toSerialize["placementId"] = o.PlacementId
	toSerialize["volumeId"] = o.VolumeId
	toSerialize["sourceNodeId"] = o.SourceNodeId
	toSerialize["targetNodeId"] = o.TargetNodeId
	toSerialize["expectedFenceEpoch"] = o.ExpectedFenceEpoch
	toSerialize["idempotencyKey"] = o.IdempotencyKey

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RequestWorkspaceMoveDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"operationId",
		"placementId",
		"volumeId",
		"sourceNodeId",
		"targetNodeId",
		"expectedFenceEpoch",
		"idempotencyKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestWorkspaceMoveDto := _RequestWorkspaceMoveDto{}

	err = json.Unmarshal(data, &varRequestWorkspaceMoveDto)

	if err != nil {
		return err
	}

	*o = RequestWorkspaceMoveDto(varRequestWorkspaceMoveDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "operationId")
		delete(additionalProperties, "placementId")
		delete(additionalProperties, "volumeId")
		delete(additionalProperties, "sourceNodeId")
		delete(additionalProperties, "targetNodeId")
		delete(additionalProperties, "expectedFenceEpoch")
		delete(additionalProperties, "idempotencyKey")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRequestWorkspaceMoveDto struct {
	value *RequestWorkspaceMoveDto
	isSet bool
}

func (v NullableRequestWorkspaceMoveDto) Get() *RequestWorkspaceMoveDto {
	return v.value
}

func (v *NullableRequestWorkspaceMoveDto) Set(val *RequestWorkspaceMoveDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestWorkspaceMoveDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestWorkspaceMoveDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestWorkspaceMoveDto(val *RequestWorkspaceMoveDto) *NullableRequestWorkspaceMoveDto {
	return &NullableRequestWorkspaceMoveDto{value: val, isSet: true}
}

func (v NullableRequestWorkspaceMoveDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestWorkspaceMoveDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
