/*
Daytona

Daytona AI platform API Docs

API version: 1.0
Contact: support@daytona.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the HeartbeatStorageNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeartbeatStorageNode{}

// HeartbeatStorageNode struct for HeartbeatStorageNode
type HeartbeatStorageNode struct {
	// Total bytes available to the node
	CapacityBytes float32 `json:"capacityBytes"`
	// Bytes currently used by the node
	UsedBytes float32 `json:"usedBytes"`
	// Total inodes available to the node
	CapacityInodes float32 `json:"capacityInodes"`
	// Inodes currently used by the node
	UsedInodes float32 `json:"usedInodes"`
	// Non-sensitive scheduling labels
	Labels map[string]interface{} `json:"labels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _HeartbeatStorageNode HeartbeatStorageNode

// NewHeartbeatStorageNode instantiates a new HeartbeatStorageNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeartbeatStorageNode(capacityBytes float32, usedBytes float32, capacityInodes float32, usedInodes float32) *HeartbeatStorageNode {
	this := HeartbeatStorageNode{}
	this.CapacityBytes = capacityBytes
	this.UsedBytes = usedBytes
	this.CapacityInodes = capacityInodes
	this.UsedInodes = usedInodes
	return &this
}

// NewHeartbeatStorageNodeWithDefaults instantiates a new HeartbeatStorageNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeartbeatStorageNodeWithDefaults() *HeartbeatStorageNode {
	this := HeartbeatStorageNode{}
	return &this
}

// GetCapacityBytes returns the CapacityBytes field value
func (o *HeartbeatStorageNode) GetCapacityBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CapacityBytes
}

// GetCapacityBytesOk returns a tuple with the CapacityBytes field value
// and a boolean to check if the value has been set.
func (o *HeartbeatStorageNode) GetCapacityBytesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapacityBytes, true
}

// SetCapacityBytes sets field value
func (o *HeartbeatStorageNode) SetCapacityBytes(v float32) {
	o.CapacityBytes = v
}

// GetUsedBytes returns the UsedBytes field value
func (o *HeartbeatStorageNode) GetUsedBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UsedBytes
}

// GetUsedBytesOk returns a tuple with the UsedBytes field value
// and a boolean to check if the value has been set.
func (o *HeartbeatStorageNode) GetUsedBytesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedBytes, true
}

// SetUsedBytes sets field value
func (o *HeartbeatStorageNode) SetUsedBytes(v float32) {
	o.UsedBytes = v
}

// GetCapacityInodes returns the CapacityInodes field value
func (o *HeartbeatStorageNode) GetCapacityInodes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CapacityInodes
}

// GetCapacityInodesOk returns a tuple with the CapacityInodes field value
// and a boolean to check if the value has been set.
func (o *HeartbeatStorageNode) GetCapacityInodesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CapacityInodes, true
}

// SetCapacityInodes sets field value
func (o *HeartbeatStorageNode) SetCapacityInodes(v float32) {
	o.CapacityInodes = v
}

// GetUsedInodes returns the UsedInodes field value
func (o *HeartbeatStorageNode) GetUsedInodes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UsedInodes
}

// GetUsedInodesOk returns a tuple with the UsedInodes field value
// and a boolean to check if the value has been set.
func (o *HeartbeatStorageNode) GetUsedInodesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedInodes, true
}

// SetUsedInodes sets field value
func (o *HeartbeatStorageNode) SetUsedInodes(v float32) {
	o.UsedInodes = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *HeartbeatStorageNode) GetLabels() map[string]interface{} {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]interface{}
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeartbeatStorageNode) GetLabelsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]interface{}{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *HeartbeatStorageNode) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]interface{} and assigns it to the Labels field.
func (o *HeartbeatStorageNode) SetLabels(v map[string]interface{}) {
	o.Labels = v
}

func (o HeartbeatStorageNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HeartbeatStorageNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["capacityBytes"] = o.CapacityBytes
	toSerialize["usedBytes"] = o.UsedBytes
	toSerialize["capacityInodes"] = o.CapacityInodes
	toSerialize["usedInodes"] = o.UsedInodes
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HeartbeatStorageNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"capacityBytes",
		"usedBytes",
		"capacityInodes",
		"usedInodes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHeartbeatStorageNode := _HeartbeatStorageNode{}

	err = json.Unmarshal(data, &varHeartbeatStorageNode)

	if err != nil {
		return err
	}

	*o = HeartbeatStorageNode(varHeartbeatStorageNode)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "capacityBytes")
		delete(additionalProperties, "usedBytes")
		delete(additionalProperties, "capacityInodes")
		delete(additionalProperties, "usedInodes")
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHeartbeatStorageNode struct {
	value *HeartbeatStorageNode
	isSet bool
}

func (v NullableHeartbeatStorageNode) Get() *HeartbeatStorageNode {
	return v.value
}

func (v *NullableHeartbeatStorageNode) Set(val *HeartbeatStorageNode) {
	v.value = val
	v.isSet = true
}

func (v NullableHeartbeatStorageNode) IsSet() bool {
	return v.isSet
}

func (v *NullableHeartbeatStorageNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeartbeatStorageNode(val *HeartbeatStorageNode) *NullableHeartbeatStorageNode {
	return &NullableHeartbeatStorageNode{value: val, isSet: true}
}

func (v NullableHeartbeatStorageNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeartbeatStorageNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
