export const LOCAL_FIRST_MOVE_RECONCILER = Symbol('LOCAL_FIRST_MOVE_RECONCILER')
export const LOCAL_FIRST_MOVE_RUNTIME = Symbol('LOCAL_FIRST_MOVE_RUNTIME')
export const LOCAL_FIRST_MOVE_BATCH_SIZE = Symbol('LOCAL_FIRST_MOVE_BATCH_SIZE')
